---
name: Bug report
title: Create a report to help us improve
description: "Help us enhance our product by reporting bugs you encounter."
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: "### Issue Summary\n<!-- A concise summary can significantly help us pinpoint the issue faster. -->"

  - type: input
    id: go2rtc-version
    attributes:
      label: go2rtc Version
      description: "Identify the version of go2rtc you're encountering the bug with."
      placeholder: "e.g., 1.9.0"
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System & Version
      description: "The OS and its version where the bug was observed."
      placeholder: "e.g., Ubuntu 20.04, Windows 10"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Version (if applicable)
      description: "Mention your browser and version if this is relevant to the bug."
      placeholder: "e.g., Firefox 89.0"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "### Camera and Stream Details\n<!-- Providing specific details here helps us replicate setups more accurately. -->"

  - type: input
    id: camera-brand-model
    attributes:
      label: Camera Brand & Model
      description: "The make and model of your camera can be crucial information."
      placeholder: "e.g., Axis P3375-LVE"
    validations:
      required: true

  - type: input
    id: firmware-version
    attributes:
      label: Firmware Version
      description: "Camera's firmware version could be key in diagnosing issues."
      placeholder: "e.g., 9.12.1"
    validations:
      required: true

  - type: checkboxes
    id: issue-type
    attributes:
      label: Type of Issue
      description: "Select the types of issue(s) you are experiencing."
      options:
        - label: Two-Way Audio Support
        - label: RTSP Stream Issues
        - label: Stream Disruption on View Change
        - label: Security Concerns
        - label: Other (Please describe below)
    validations:
      required: true

  - type: textarea
    id: rtsp-url-format
    attributes:
      label: RTSP URL Format (Generalized)
      description: "Share the format of RTSP URLs being used, omitting sensitive data."
      placeholder: "rtsp://[USERNAME]:[PASSWORD]@[IP_ADDRESS]/[STREAM_PATH]"
    validations:
      required: false

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce the Issue
      description: "Detail the steps taken to encounter the bug."
      placeholder: "1. Configuration setup\n2. Commands executed\n3. Behavior witnessed"
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual Behavior
      description: "Describe what you anticipated versus what actually occurred."
      placeholder: "- Expected: \n- Actual:"
    validations:
      required: true

  - type: textarea
    id: av-support
    attributes:
      label: Audio/Video Issue Details
      description: "Clarify if the issue pertains to audio/video functionalities."
      placeholder: "- Two-way audio support: Yes/No\n- RTSP stream compatibility: Yes/No"
    validations:
      required: false

  - type: textarea
    id: security-concerns
    attributes:
      label: Security Concerns Detailed
      description: "If applicable, outline any potential security vulnerabilities."
      placeholder: "Yes/No\nDetails (avoid sensitive info):"
    validations:
      required: false

  - type: textarea
    id: logs-context
    attributes:
      label: Logs & Additional Context
      description: "Attach any logs or screenshots that could help diagnose the issue."
      placeholder: "Include any relevant logs or error messages."
    validations:
      required: false

  - type: textarea
    id: potential-solution
    attributes:
      label: Suggested Fix (Optional)
      description: "If you have an idea for solving the issue, we'd love to hear it."
      placeholder: "Possible approach to resolve the bug..."
    validations:
      required: false
