---
name: Documentation Improvement
description: Help us enhance our documentation with your suggestions or by pointing out inaccuracies.
labels: ["documentation", "improvement"]

body:
  - type: markdown
    attributes:
      value: "### Documentation Issue Summary\n<!-- Please provide a clear and concise summary of the issue or the inaccuracy you've encountered. -->"

  - type: textarea
    id: issue-description
    attributes:
      label: Detailed Issue Description
      description: "Provide a detailed description of the issue or inaccuracy with the documentation."
      placeholder: "Describe the specific issue or inaccuracy you've identified..."
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Detailed Suggested Improvement
      description: "Offer a detailed suggestion for how we can improve the documentation."
      placeholder: "Please detail your proposed improvements or corrections..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: "Provide any additional context that could help us understand the problem better, such as links to the documentation in question or screenshots illustrating the issue."
      placeholder: "Links to documentation, screenshots, etc., that might help clarify the issue or your suggestion..."
    validations:
      required: false
