name: Feature Request
description: Suggest an idea for this project
labels: ["issue:enhancement"]

body:
  - type: markdown
    attributes:
      value: "### Is your feature request related to a problem? Please describe.\n<!-- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] -->"

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: desired-solution
    attributes:
      label: Desired Solution
      description: "A clear and concise description of what you want to happen."
      placeholder: "I would like..."
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Another solution could be..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Any additional information, links, or screenshots that might help..."
    validations:
      required: false
