name: Feature Request
description: Share your ideas or suggest new features to improve the project.
labels: ["type:enhancement", "status:review needed"]

body:
  - type: markdown
    attributes:
      value: "### Feature Request Overview\n<!-- Please provide a clear and concise description of the problem your feature request is addressing or the new feature you are proposing. -->"

  - type: textarea
    id: problem-description
    attributes:
      label: Problem or Opportunity Description
      description: "Describe the problem you're facing or the opportunity for improvement. Be as specific as possible."
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: desired-solution
    attributes:
      label: Proposed Solution
      description: "Describe what you would like to happen that would solve this problem or seize this opportunity."
      placeholder: "Ideally, I would like..."
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Considered Alternatives
      description: "Describe any alternative solutions or features you've considered. Why might these alternatives be less desirable?"
      placeholder: "Another potential solution could be..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context and Information
      description: "Provide any other context, links, or screenshots that might help clarify your feature request or idea."
      placeholder: "Additional details, context, or screenshots..."
    validations:
      required: false
