name: Setup/Configuration Issue
description: Report and get help with issues encountered during setup or configuration of the software.
labels: ["issue:setup", "status:needs triage"]

body:
  - type: markdown
    attributes:
      value: "### Issue Overview\n<!-- Provide a clear and concise description of the issue you're encountering with setup or configuration. -->"

  - type: textarea
    id: issue-description
    attributes:
      label: Detailed Issue Description
      description: "Explain the issue in detail, including what you were trying to achieve."
      placeholder: "When I try to set up..., I encounter..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Reproduction Steps\n<!-- Detail the steps taken to encounter the issue, which will help in diagnosing the problem more effectively. -->"

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Exact Steps to Reproduce
      description: "Please list the steps needed to reproduce the issue."
      placeholder: "1. Navigate to '...'\n2. Execute command '....'\n3. Adjust configuration setting '....'\n4. Observe the resulting behavior"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Outcome
      description: "Describe what you expected to happen after following the steps above."
      placeholder: "Following these steps, I expected..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Observed Outcome
      description: "Describe what actually happened instead."
      placeholder: "However, the actual outcome was..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### System Environment\n<!-- It's important to know the environment in which the issue occurred. Please provide as much detail as possible. -->"

  - type: input
    id: software-version
    attributes:
      label: Software Version
      description: "The version of the software you're using where the issue occurred."
      placeholder: "e.g., 1.9.0"
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System & Version
      description: "The operating system and its version where the issue was encountered."
      placeholder: "e.g., macOS Big Sur 11.2.3"
    validations:
      required: true

  - type: textarea
    id: specific-configurations
    attributes:
      label: Configuration Details
      description: "Any specific configurations that might be relevant to the issue."
      placeholder: "Include any modified settings or custom configurations here..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: "Provide any other context about the problem, such as logs, error messages, or screenshots."
      placeholder: "Attach logs, error messages, or screenshots here to provide more context..."
    validations:
      required: false
