name: Setup/Configuration Issue
description: Report issues related to setting up or configuring the software
labels: ["issue:setup"]

body:
  - type: markdown
    attributes:
      value: "### Describe the Setup/Configuration Issue\n<!-- A clear and concise description of what the issue is. -->"

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: "A clear and concise description of what the issue is."
      placeholder: "Describe the issue..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Steps to Reproduce\n<!--\n1. Go to '...'\n2. Run command '....'\n3. Modify configuration '....'\n4. See error\n-->"

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: "1. Go to '...'\n2. Run command '....'\n3. Modify configuration '....'\n4. See error"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: "I expected that..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: "A clear and concise description of what actually happened."
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Environment\n<!-- Include as many relevant details about the environment where the issue occurred -->"

  - type: input
    id: go2rtc-version
    attributes:
      label: go2rtc version
      description: "The version of go2rtc you are using."
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System and Version
      description: "Your operating system and version."
      placeholder: "e.g., Ubuntu 20.04"
    validations:
      required: true

  - type: textarea
    id: specific-configurations
    attributes:
      label: Specific Configurations
      description: "Any specific configurations related to the issue."
      placeholder: "Details about your configuration..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context about the problem here, such as logs, screenshots, etc."
      placeholder: "Any additional information, links, or screenshots that might help..."
    validations:
      required: false
