# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Go2rtc < Formula
    desc "Ultimate camera streaming application with support RTSP, WebRTC, HomeKit, FFmpeg, RTMP, etc."
    homepage "https://github.com/AlexxIT/go2rtc"
    version "1.3.1"
    head "https://github.com/AlexxIT/go2rtc.git", branch: "master"


    bottle do
        sha256 cellar: :any_skip_relocation, arm64_ventura: "31fa5da8a98ee1d52c677c14c4d012f62809d39a6345162f6aa4e00c94e2f90c"


    depends_on "go" => :build
  
    on_macos do
        if Hardware::CPU.intel?
            url "https://github.com/AlexxIT/go2rtc/releases/download/v1.3.1/go2rtc_mac_amd64.zip"
            sha256 "31fa5da8a98ee1d52c677c14c4d012f62809d39a6345162f6aa4e00c94e2f90c"
  
            def install
                bin.install "go2rtc"
            end
        end
        if Hardware::CPU.arm?
            url "https://github.com/AlexxIT/go2rtc/releases/download/v1.3.1/go2rtc_mac_arm64.zip"
            sha256 "8976b2f7b11acfdc2bc666b047e6fa30d9a309aac4efa035d651cf2e6d344036"
  
            def install
                bin.install "go2rtc"
            end
        end
    end
  
    on_linux do
      if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
        url "https://github.com/AlexxIT/go2rtc/releases/download/v1.3.1/go2rtc_linux_arm"
        sha256 "b6fe41288475f24c2e5d691b061abedc638644480018cd31148d10d1e3b0cef6"
  
        def install
          bin.install "go2rtc_linux_arm" => "go2rtc"
        end
      end
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/AlexxIT/go2rtc/releases/download/v1.3.1/go2rtc_linux_arm64"
        sha256 "319fdd38e285f27a382a27bc009e5a1917f8c7ce053bcbb04a2b3a1073374ffe"
  
        def install
          bin.install "go2rtc_linux_arm64" => "go2rtc"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/AlexxIT/go2rtc/releases/download/v1.3.1/go2rtc_linux_amd64"
        sha256 "59e7ec83d017b03a241d964297d8764ccde8d6ae7f1050186268d774d853253b"
  
        def install
          bin.install "go2rtc_linux_amd64" => "go2rtc"
        end
      end
    end

    def install
        system "go", "build", "-ldflags", "-s -w", "-trimpath", "-o", "go12rtc"
        bin.install "go12rtc"
  
    test do
      system "#{bin}/go2rtc", "--version"
    end
  end
  